# Generated by Django 3.1.1 on 2021-06-29 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50)),
                ('UserFirstName', models.CharField(default='', max_length=50)),
                ('UserLastName', models.CharField(default='', max_length=50)),
                ('ProfileImage', models.ImageField(default='default.jpg', upload_to='app/images')),
                ('Gender', models.CharField(default='male', max_length=10)),
                ('UserEmail', models.EmailField(default='', max_length=254)),
                ('Hobbies', models.CharField(default='Cricket', max_length=200)),
                ('Ressidence', models.CharField(default='Dikshanti app.', max_length=2000)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=2000)),
                ('incident_date', models.DateField(null=True)),
                ('incident_time', models.TimeField(null=True)),
                ('incident_location', models.CharField(default='', max_length=2000)),
                ('severity', models.CharField(default='', max_length=200)),
                ('cause', models.CharField(default='', max_length=2000)),
                ('actions', models.CharField(default='', max_length=2000)),
                ('type_env', models.BooleanField(default=False)),
                ('type_injury', models.BooleanField(default=False)),
                ('type_property', models.BooleanField(default=False)),
                ('type_vehicle', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
